<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Master Code</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/ressources/css/tailwind.output.css" />
  <style>
    dialog[open] {
      animation: appear .15s cubic-bezier(0, 1.8, 1, 1.8);
    }

    dialog::backdrop {
      background: linear-gradient(45deg, rgba(0, 0, 0, 0.5), rgba(54, 54, 54, 0.5));
      backdrop-filter: blur(3px);
    }


    @keyframes appear {
      from {
        opacity: 0;
        transform: translateX(-3rem);
      }

      to {
        opacity: 1;
        transform: translateX(0);
      }
    }
  </style>
  </style>
  <script src="/ressources/js/alpine.min.js" defer></script>
  <script src="/ressources/js/init-alpine.js"></script>
  <link rel="stylesheet" href="/ressources/css/Chart.min.css" />
  <script src="/ressources/js/Chart.min.js" defer></script>
  <script src="/ressources/js/charts-lines.js" defer></script>
  <script src="/ressources/js/charts-pie.js" defer></script>
  <script src="/ressources/js/focus-trap.js" defer></script>
</head>

<body>
  <?php $page = "";
  $page = "articles"; ?>
  <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
    <?php
    include_once "../App/Views/admin/partials/navbar/nav-left.phtml";
    ?>
    <div class="flex flex-col flex-1 w-full">

      <?php
      include_once "../App/Views/admin/partials/navbar/nav-top.phtml"
      ?>
      <main class="h-full pb-16 overflow-y-auto">
        <div class="w-full container grid px-6 mx-auto">
          <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Tables des articles
          </h2>
          <!-- With avatar @click="openModal" -->
          <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
            <div class="w-full overflow-x-auto">
              <?php if ($_SESSION["Auth"]["role"] === '0') : ?>
                <table class="w-full whitespace-no-wrap overflow-scroll">
                  <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">

                      <th class="px-4 py-3">Titre articles</th>
                      <th class="px-4 py-3">Auteur</th>
                      <th class="px-4 py-3">vue</th>
                      <th class="px-4 py-3">commentaire</th>
                      <th class="px-4 py-3">Date publication</th>
                      <th class="px-4 py-3">Derniere modif</th>
                      <th class="px-4 py-3 flex
                      justify-center items-center">Actions
                        <button @click="openModal" class="ml-2 px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                          <span class="w-2" aria-hidden="true">+</span>
                        </button>
                      </th>

                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    <?php for ($i = 0; $i < count($allArticles); $i++) : ?>
                      <tr class="text-gray-700 dark:text-gray-400">
                        <td class="px-4 py-3">
                          <div class="flex items-center text-sm">
                            <!-- Avatar with inset shadow -->
                            <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                              <img class="object-cover w-full h-full rounded-full" src="/ressources/images/images_principales/<?= $allArticles[$i]['article_image'] ?>" alt="image" loading="lazy" />
                              <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                            </div>
                            <div>
                              <p class="font-semibold">
                                <?= $allArticles[$i]['article_title'] ?>
                              </p>
                              <p class="text-xs text-gray-600 dark:text-gray-400">
                                <?= $allArticles[$i]['category_name'] ?>
                              </p>
                            </div>
                          </div>
                        </td>

                        <td class="px-4 py-3 text-sm">
                          <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                            <?= $allArticles[$i]['user_pseudo'] ?>
                          </span>
                        </td>
                        <td class="px-4 py-3 text-sm">
                          <?php for ($y = 0; $y < count($views); $y++) : ?>
                            <?php if ($allArticles[$i]['article_id'] === $views[$y]["article_id"]) : ?>
                              <?= $views[$y]["nombre"] ?>
                            <?php endif; ?>
                          <?php endfor; ?>
                        </td>
                        <td class="px-4 py-3 text-xs">
                          <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                            89651
                          </span>
                        </td>
                        <td class="px-4 py-3 text-sm">
                          <?= $allArticles[$i]['created_at'] ?>
                        </td>
                        <td class="px-4 py-3 text-sm">
                          <?php if ($allArticles[$i]['updated_at'] === null) : ?>
                            ---- -- --
                          <?php else : ?>
                            <?= $allArticles[$i]['updated_at'] ?>
                          <?php endif; ?>
                        </td>
                        <td class="px-4 py-3">
                          <div class="flex items-center justify-center space-x-4 text-sm">
                            <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($allArticles[$i]["article_id"]) ?>&action=<?= $this->datacrypt('updateArticle') ?>&state=<?= $this->datacrypt('publier') ?>" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit">
                              <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                </path>
                              </svg>
                            </a>
                            <!-- pour la redirection -->
                            <a href="" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit">
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                              </svg>
                            </a>
                            <!-- pour la redirection -->

                            <button onclick="document.getElementById('myModal').showModal()" id="btn" value="<?= $this->datacrypt($allArticles[$i]['article_id']) ?>" class="supprime flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
                              <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                              </svg>
                            </button>


                          </div>
                        </td>

                      </tr>
                    <?php endfor; ?>

                  </tbody>
                </table>
              <?php elseif ($_SESSION["Auth"]["role"] === '2') : ?>

                <table class="w-full whitespace-no-wrap overflow-scroll">
                  <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">

                      <th class="px-4 py-3">Titre articles</th>
                      <th class="px-4 py-3">Auteur</th>
                      <th class="px-4 py-3">Nombre de vue</th>
                      <th class="px-4 py-3">Nombre de commentaire</th>
                      <th class="px-4 py-3">Date de publication</th>
                      <th class="px-4 py-3">Derniere modification</th>
                      <th class="px-4 py-3 flex
                      justify-center items-center">Actions
                        <button @click="openModal" class="ml-2 px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                          <span class="w-2" aria-hidden="true">+</span>
                        </button>
                      </th>

                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    <?php for ($i = 0; $i < count($allArticles); $i++) : ?>
                      <?php if ($_SESSION["Auth"]["pseudo"] === $allArticles[$i]['user_pseudo']) : ?>
                        <tr class="text-gray-700 dark:text-gray-400">
                          <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                              <!-- Avatar with inset shadow -->
                              <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                <img class="object-cover w-full h-full rounded-full" src="/ressources/images/images_principales/<?= $allArticles[$i]['article_image'] ?>" alt="image" loading="lazy" />
                                <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                              </div>
                              <div>
                                <p class="font-semibold">
                                  <?= $allArticles[$i]['article_title'] ?>
                                </p>
                                <p class="text-xs text-gray-600 dark:text-gray-400">
                                  <?= $allArticles[$i]['category_name'] ?>
                                </p>
                              </div>
                            </div>
                          </td>

                          <td class="px-4 py-3 text-sm">
                            <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                              <?= $allArticles[$i]['user_pseudo'] ?>
                            </span>
                          </td>
                          <td class="px-4 py-3 text-sm">
                            <?php for ($y = 0; $y < count($views); $y++) : ?>
                              <?php if ($allArticles[$i]['article_id'] === $views[$y]["article_id"]) : ?>
                                <?= $views[$y]["nombre"] ?>
                              <?php endif; ?>
                            <?php endfor; ?>
                          </td>
                          <td class="px-4 py-3 text-xs">
                            <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                              89651
                            </span>
                          </td>
                          <td class="px-4 py-3 text-sm">
                            <?= $allArticles[$i]['created_at'] ?>
                          </td>
                          <td class="px-4 py-3 text-sm">
                            <?php if ($allArticles[$i]['updated_at'] === null) : ?>
                              ---- -- --
                            <?php else : ?>
                              <?= $allArticles[$i]['updated_at'] ?>
                            <?php endif; ?>
                          </td>
                          <td class="px-4 py-3">
                            <div class="flex items-center space-x-4 text-sm">
                              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($allArticles[$i]["article_id"]) ?>&action=<?= $this->datacrypt('updateArticle') ?>&state=<?= $this->datacrypt('publier') ?>" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit">
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                  </path>
                                </svg>
                              </a>

                              <!-- pour la redirection -->
                              <a href="" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                  <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                                </svg>
                              </a>
                              <!-- pour la redirection -->

                              <button value="<?= $this->datacrypt($allArticles[$i]['article_id']) ?>" class="supprime flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                  <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                                </svg>
                              </button>
                            </div>
                          </td>

                        </tr>
                      <?php endif; ?>
                    <?php endfor; ?>

                  </tbody>
                </table>
              <?php endif; ?>

              <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">
                <!-- Modal -->
                <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0 transform translate-y-1/2" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0  transform translate-y-1/2" @click.away="closeModal" @keydown.escape="closeModal" class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl" role="dialog" id="modal">
                  <!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
                  <header class="flex justify-end">
                    <button class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700" aria-label="close" @click="closeModal">
                      <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
                        <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path>
                      </svg>
                    </button>
                  </header>
                  <!-- Modal body -->
                  <div class="mt-4 mb-6">
                    <!-- Modal title -->
                    <p class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300">
                      Ajouter un article
                    </p>
                    <!-- Modal description -->
                    <div class="text-sm text-gray-700 dark:text-gray-400">
                      <h3 class="mb-2">Selectionnez une catégorie pour votre article</h3>
                      <select name="categorie" id="categorie" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                        <option value="defaut">Choisir une categorie d'article</option>
                        <?php foreach ($allCategories as $key => $values) : ?>
                          <option value=<?= $values["category_id"] ?>> <?= $values["category_name"] ?></option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                  </div>
                  <footer class="flex flex-col items-center justify-end px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
                    <button @click="closeModal" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                      Annuler
                    </button>
                    <button class="redirect w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                      Aller sur l'éditeur
                    </button>
                  </footer>
                </div>
              </div>
            </div>
            <div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">

              <dialog id="myModal" class="h-auto w-1/4 md:w-1/2 p-5 dark:bg-gray-800 overflow-hidden  bg-white rounded-md ">

                <div class="flex flex-col w-full h-auto ">
                  <!-- Header -->
                  <div class="flex w-full h-auto justify-between items-center">
                    <div class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300 text-center flex  justify-center items-center">
                      <img src="ressources/images/icons-warning.png" alt=""> <span class="dark:text-white">Warning</span>
                    </div>
                    <div onclick="document.getElementById('myModal').close();" class="focus:outline-none focus:shadow-outline-gray inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-white hover: hover:text-gray-700 text-white">
                      <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
                        <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path>
                      </svg>
                    </div>
                    <!--Header End-->
                  </div>
                  <!-- Modal Content-->
                  <div class="text-sm text-center text-gray-700 dark:text-gray-400 ">
                    <h3 class="mb-2 uppercase">Etes vous sure ?</h3>
                    <p class="dark:text-gray-700">Vous désirez vraiment supprimer cet article
                      définitivement ? Vous etes libre, mais retenez tout simplement
                      que cette action est irréversible
                    </p>
                  </div>
                  <!-- End of Modal Content-->

                  <footer class="flex flex-col items-center justify-center px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
                    <button onclick="document.getElementById('myModal').close();" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                      Annuler
                    </button>
                    <button class="redirect w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-red-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-red-600 hover:bg-rose-700 focus:outline-none focus:shadow-outline-purple">
                      Supprimer définitivement
                    </button>
                  </footer>

                </div>
              </dialog>

            </div>


          </div>
        </div>
      </main>
    </div>
  </div>
</body>
<script src="/ressources/js/article_js.js"></script>
<!-- <script src="/ressources/js/search.js"></script> -->
<script src="/ressources/js/searchGeneral.js"></script>

</html>