<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Master Code</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="/ressources/css/tailwind.output.css" />
    <script src="/ressources/js/alpine.min.js" defer></script>
    <script src="/ressources/js/init-alpine.js"></script>
    <link rel="stylesheet" href="/ressources/css/Chart.min.css" />
    <script src="/ressources/js/Chart.min.js" defer></script>
    <script src="/ressources/js/charts-lines.js" defer></script>
    <script src="/ressources/js/charts-pie.js" defer></script>
    <script src="/ressources/js/focus-trap.js" defer></script>
</head>

<body>

    <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
        <?php
        include_once "../App/Views/admin/partials/navbar/nav-left.phtml";
        ?>
        <div class="flex flex-col flex-1 w-full">

            <?php
            include_once "../App/Views/admin/partials/navbar/nav-top.phtml"
            ?>
            <main class="main-contain h-full pb-16 overflow-y-auto">
                <div class="container grid px-6 mx-auto">
                    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
                        Brouillons des articles
                    </h2>
                    <!-- With avatar @click="openModal" -->
                    <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
                        <div class="w-full overflow-x-auto">

                            <table class="w-full whitespace-no-wrap">
                                <thead>
                                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">

                                        <th class="px-4 py-3">Titre articles</th>
                                        <th class="px-4 py-3">Auteur</th>

                                        <th class="px-4 py-3">Date d'édition</th>
                                        <th class="px-4 py-3">Derniere modification</th>
                                        <th class="px-4 py-3 text-center">Actions

                                        </th>

                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                                    <?php foreach ($allArticles as $key => $values) : ?>
                                        <tr class="text-gray-700 dark:text-gray-400">
                                            <td class="px-4 py-3">
                                                <div class="flex items-center text-sm">
                                                    <!-- Avatar with inset shadow -->
                                                    <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                                        <img class="object-cover w-full h-full rounded-full" src="/ressources/images/images_principales/<?= $values['article_image'] ?>" alt="image" loading="lazy" />
                                                        <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                                                    </div>
                                                    <div>
                                                        <p class="font-semibold">
                                                            <?= $values['article_title'] ?>
                                                        </p>
                                                        <p class="text-xs text-gray-600 dark:text-gray-400">
                                                            <?= $values['category_name'] ?>
                                                        </p>
                                                    </div>
                                                </div>
                                            </td>

                                            <td class="px-4 py-3 text-sm">
                                                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                                    <?= $values['user_pseudo'] ?>
                                                </span>
                                            </td>

                                            <td class="px-4 py-3 text-sm">
                                                <?= $values['created_at'] ?>
                                            </td>
                                            <td class="px-4 py-3 text-sm">
                                                <?php if ($values['updated_at'] === null) : ?>
                                                    ---- -- --
                                                <?php else : ?>
                                                    <?= $values['updated_at'] ?>
                                                <?php endif; ?>

                                            </td>
                                            <td class="px-4 py-3 text-center m-auto">
                                                <div class="flex items-center justify-center space-x-4 text-sm m-auto text-center">
                                                    <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('modalArticle') ?>" class="modalView flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit" id="">
                                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                        </svg>

                                                    </a>

                                                    <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('updateArticle') ?>" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Edit">
                                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                                            </path>
                                                        </svg>
                                                    </a>

                                                    <button @click="openModal" class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
                                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                                                        </svg>
                                                    </button>

                                                    <button value="<?= $this->datacrypt($values['article_id']) ?>" class="publier flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
                                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                                                        </svg> Publier
                                                        </span>
                                                    </button>
                                                </div>
                                            </td>

                                        </tr>
                                    <?php endforeach; ?>

                                </tbody>
                            </table>

                            <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">
                                <!-- Modal -->
                                <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0 transform translate-y-1/2" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0  transform translate-y-1/2" @click.away="closeModal" @keydown.escape="closeModal" class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl" role="dialog" id="modal">
                                    <!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
                                    <header class="flex justify-end">
                                        <button onclick="openModal(true)" class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700" aria-label="close" @click="closeModal">
                                            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
                                                <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path>
                                            </svg>
                                        </button>
                                    </header>
                                    <!-- Modal body -->
                                    <div class="mt-4 mb-6 text-center">
                                        <!-- Modal title -->
                                        <div class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300 text-center flex  justify-center items-center">
                                            <img src="ressources/images/icons-warning.png" alt=""> <span class="dark:text-white">Warning</span>
                                        </div>
                                        <!-- Modal description -->
                                        <div class="text-sm text-gray-700 dark:text-gray-400">
                                            <h3 class="mb-2">Etes vous sure ?</h3>
                                            <p class="dark:text-gray-700">Vous désirez vraiment supprimer cet article des brouillons ? Vous etes libre, mais retenez tout simplement
                                                que cette action est irréversible
                                            </p>
                                        </div>
                                    </div>
                                    <footer class="flex flex-col items-center justify-center px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
                                        <button @click="closeModal" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                                            Annuler
                                        </button>
                                        <button class="redirect w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-red-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-red-600 hover:bg-rose-700 focus:outline-none focus:shadow-outline-purple">
                                            Supprimer définitivement
                                        </button>
                                    </footer>
                                </div>
                            </div>
                        </div>
                        <div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">

                            <span class="col-span-2"></span>

                        </div>
                        
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>
<script src="/ressources/js/broullons.js"></script>
<!-- <script src="/ressources/js/search.js"></script> -->
<script src="/ressources/js/searchGeneral.js"></script>
<script> 
    const button = document.getElementById('buttonmodal')
    const closebutton = document.getElementById('closebutton')
    const modal = document.getElementById('modal')

    button.addEventListener('click',()=>modal.classList.add('scale-100'))
    closebutton.addEventListener('click',()=>modal.classList.remove('scale-100'))
</script>
</html>