<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Master Code</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/ressources/css/tailwind.output.css" />
  <script src="/ressources/js/alpine.min.js" defer></script>
  <script src="/ressources/js/init-alpine.js"></script>
  <link rel="stylesheet" href="/ressources/css/Chart.min.css" />
  <script src="/ressources/js/Chart.min.js" defer></script>
  <link rel="shortcut icon" href="ressources/images/web.svg" />
  <script src="ressources/tinymce/tinymce.min.js"></script>
  <script src="/ressources/js/charts-lines.js" defer></script>
  <script src="/ressources/js/charts-pie.js" defer></script>
  <script type="text/javascript">
   

   tinymce.init({
      selector: '#mytextarea',
      // skin: (window.matchMedia("(prefers-color-scheme: dark)").matches ? "oxide-dark" : ""),
      // content_css: (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : ""),
      toolbar_mode: 'sliver',
      language : 'fr_FR',
      // draggable_modal: true,
      // toolbar_persist: true,
      // menubar: 'file edit insert view format table tools help',
      plugins:'advlist autoresize codesample directionality emoticons fullscreen hr image link lists media table toc wordcount',
      toolbar:'undo redo removeformat hr | formatselect fontsizeselect | rtl ltr bold italic | alignjustify alignright aligncenter alignleft| numlist bullist | forecolor backcolor | blockquote table | image link media codesample emoticons | wordcount fullscreen',
      // toolbar : 'undo redo removeformat | formatselect fontsizeselect | bold italic | rtl ltr | alignjustify alignright aligncenter alignleft | numlist bullist | forecolor backcolor | blockquote table toc hr | image link media codesample emoticons | wordcount fullscreen',
      // skin: typeof theme !== 'undefined' F ? theme : 'light',
    // block_formats: 'Paragraph=p; Header 1=h1; Header 2=h2; Header 3=h3',
    branding: false,
    toolbar_sticky: false,
    upload_directory: null,
     automatic_uploads: true,
//      skin: (window.matchMedia("(theme-dark: dark )").matches ? "oxide-dark" : ""),
    //  skin: "oxide-dark",
// content_css: "dark",

    });

  </script>
</head>

<body>
<?php $page = "";
$page = "editor";?>
  <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
    <?php
include_once "../App/Views/admin/partials/navbar/nav-left.phtml";
?>
    <div class="flex flex-col flex-1 w-full">

      <?php
include_once "../App/Views/admin/partials/navbar/nav-top.phtml"
?>
      <main class="h-full overflow-y-auto">
      <div class="container grid px-6 mx-auto mt-10">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Editeur d'articles
          </h2>
        <?php include_once "../App/Views/admin/admin_components/editor_panel.phtml"?>
      </div>
      </main>
    </div>
  </div>
  </script>

</body>
  </body>