<!-- <section class="antialiased bg-gray-100 text-gray-600 h-screen px-4 w-screen"> -->
<div>
    <!-- Table -->
    <div
        class="dark:border-gray-700 bg-gray-50 dark:text-white dark:text-gray-400 dark:bg-gray-800 w-full max-w-3/6 bg-white shadow-lg rounded-sm border border-gray-200">

        <div class="p-3">
            <div class="overflow-x-auto">
                <table class="table-auto w-full ">
                    <tbody class="text-sm divide-y divide-gray-100">
                        <?php @session_start(); ?>
                        <?php if ($_SESSION["Auth"]["role"] === '0'): ?>
                            <?php foreach ($users as $user => $values) { ?>
                                <tr>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <div class="w-10 h-10 flex-shrink-0 mr-2 sm:mr-3">
                                                <div class="accountHeader object-cover w-8 h-8 rounded-full flex justify-center items-center border-gray-800"
                                                    style="text-transform: uppercase; background-color: <?= $values["user_bgc"] ?>;">
                                                    <span class="text-white">
                                                        <?php $pseudo = $values['user_pseudo'];
                                                        echo $pseudo[0]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="font-medium text-gray-800 dark:text-white">
                                                <?php echo $values['user_pseudo'] ?>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap ">
                                        <div class="text-left">
                                            <?php echo $values['user_email'] ?>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="text-left font-medium text-green-500">
                                            <?php if ($values["user_role"] == 0): ?>
                                                <span
                                                    class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
                                                    Administrateur
                                                </span>
                                            <?php elseif ($values["user_role"] == 1): ?>
                                                <span
                                                    class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-white">
                                                    Lecteur
                                                </span>
                                            <?php else: ?>
                                                <span
                                                    class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-white">
                                                    Rédacteur
                                                </span>
                                            <?php endif; ?>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="text-lg text-center">
                                            <?php if ($values["user_pseudo"] !== "SuperAdmin"): ?>
                                                <div class="flex items-center space-x-4 text-sm">
                                                    <button
                                                        class="supprimeUser flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                        value="<?= $this->datacrypt($values["user_id"]) ?>" aria-label="Delete">
                                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor"
                                                            viewBox="0 0 20 20">
                                                            <path fill-rule="evenodd"
                                                                d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                                clip-rule="evenodd"></path>
                                                        </svg>
                                                    </button>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>

                            <?php foreach ($categories as $categorie => $values) { ?>
                                <tr>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <img class="rounded-full"
                                                src="/ressources/images/categories_images/<?= $values["category_img"] ?>"
                                                width="40" height="40" alt="Philip Harbach"
                                                style="margin-right: 3px; width: 40px;height:40px">
                                            <div class="font-medium text-gray-800 dark:text-white">
                                                <?php echo $values['category_name'] ?>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap ">
                                        <span
                                            class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                            <?php echo $values['category_description'] ?>
                                        </span>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="text-left font-medium text-green-500">
                                            <span
                                                class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
                                                Catégorie d'article
                                            </span>

                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center space-x-4 text-sm">
                                            <button
                                                class="editer flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                aria-label="Edit" value="<?= $this->datacrypt($values["category_id"]) ?>">
                                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                    <path
                                                        d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                                    </path>
                                                </svg>
                                            </button>
                                            <button
                                                class="supprimerCat flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                aria-label="Delete" value="<?= $this->datacrypt($values["category_id"]) ?>">
                                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                    <path fill-rule="evenodd"
                                                        d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                        clip-rule="evenodd"></path>
                                                </svg>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php foreach ($contacts as $contact => $values) { ?>
                                <tr>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <img class="rounded-full" src="/ressources/images/contacts.png" width="40"
                                                height="40" alt="Philip Harbach" style="margin-right: 3px;">
                                            <div class="font-medium text-gray-800 dark:text-white">
                                                <?php echo $values['contact_name'] ?>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap ">
                                        <div class="text-left">
                                            <?php echo $values['contact_email'] ?>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="text-left font-medium text-green-500">
                                            <span
                                                class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
                                                Contacts par formulaire
                                            </span>

                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center space-x-4 text-sm">
                                            <?php if ($values["state"] === "attente"): ?>
                                                <button @click="openModal" value="<?= $this->datacrypt($values["contact_id"]) ?>"
                                                    class="sms flex items-center justify-between  py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                    aria-label="Edit">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                        <path stroke-linecap="round" stroke-linejoin="round"
                                                            d="M21.75 9v.906a2.25 2.25 0 01-1.183 1.981l-6.478 3.488M2.25 9v.906a2.25 2.25 0 001.183 1.981l6.478 3.488m8.839 2.51l-4.66-2.51m0 0l-1.023-.55a2.25 2.25 0 00-2.134 0l-1.022.55m0 0l-4.661 2.51m16.5 1.615a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V8.844a2.25 2.25 0 011.183-1.98l7.5-4.04a2.25 2.25 0 012.134 0l7.5 4.04a2.25 2.25 0 011.183 1.98V19.5z" />
                                                    </svg>
                                                </button>
                                            <?php else: ?>
                                                <button value="<?= $this->datacrypt($values["contact_id"]) ?>"
                                                    class="supprimerCont flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                    aria-label="Delete">
                                                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                        <path fill-rule="evenodd"
                                                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                            clip-rule="evenodd"></path>
                                                    </svg>
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php foreach ($articles as $article => $values): ?>
                                <tr>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <img class="rounded-full"
                                                src="/ressources/images/images_principales/<?= $values['article_image'] ?>"
                                                alt="Philip Harbach" style="margin-right: 3px; width: 40px;height:40px">
                                            <div class="font-medium text-gray-800 dark:text-white">
                                                <?= $values['article_title'] ?>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap ">
                                        <span
                                            class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">

                                            Catégorie :
                                            <?= $values['category_name']; ?>
                                        </span>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="text-left font-medium text-green-500">
                                            <span
                                                class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
                                                Articles
                                            </span>

                                        </div>
                                    </td>
                                    <td class="p-2 whitespace-nowrap">
                                        <div class="flex items-center space-x-4 text-sm">
                                            <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('updateArticle') ?>&state=<?= $this->datacrypt('publier') ?>"
                                                class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                aria-label="Edit">
                                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                    <path
                                                        d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                                    </path>
                                                </svg>
                                            </a>

                                            <!-- pour la redirection -->
                                            <a href="?goto=<?= $this->datacrypt('home') ?>&articleid=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('articleOne') ?>"
                                                class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                aria-label="Edit">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                    stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                        d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                                                </svg>
                                            </a>
                                            <!-- pour la redirection -->

                                            <button onclick="document.getElementById('myModal').showModal()" id="btn"
                                                value="<?= $this->datacrypt($values['article_id']) ?>"
                                                class="supprimerArt flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                aria-label="Delete">
                                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                    <path fill-rule="evenodd"
                                                        d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                        clip-rule="evenodd"></path>
                                                </svg>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php if ($_SESSION["Auth"]["role"] === '2'): ?>
                            <?php foreach ($articles as $article => $values): ?>
                                <?php if ($_SESSION["Auth"]["pseudo"] === $values["user_pseudo"]): ?>
                                    <tr>
                                        <td class="p-2 whitespace-nowrap">
                                            <div class="flex items-center">
                                                <img class="rounded-full"
                                                    src="/ressources/images/images_principales/<?= $values['article_image'] ?>"
                                                    alt="Philip Harbach" style="margin-right: 3px; width: 40px;height:40px">
                                                <div class="font-medium text-gray-800 dark:text-white">
                                                    <?= $values['article_title'] ?>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="p-2 whitespace-nowrap ">
                                            <span
                                                class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">

                                                Catégorie :
                                                <?= $values['category_name']; ?>
                                            </span>
                                        </td>
                                        <td class="p-2 whitespace-nowrap">
                                            <div class="text-left font-medium text-green-500">
                                                <span
                                                    class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
                                                    Articles
                                                </span>

                                            </div>
                                        </td>
                                        <td class="p-2 whitespace-nowrap">
                                            <div class="flex items-center space-x-4 text-sm">
                                                <a href="?goto=<?= $this->datacrypt('dashboard') ?>&id=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('updateArticle') ?>&state=<?= $this->datacrypt('publier') ?>"
                                                    class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                    aria-label="Edit">
                                                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                        <path
                                                            d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                                                        </path>
                                                    </svg>
                                                </a>

                                                <!-- pour la redirection -->
                                                <a href="?goto=<?= $this->datacrypt('home') ?>&articleid=<?= $this->datacrypt($values["article_id"]) ?>&action=<?= $this->datacrypt('articleOne') ?>"
                                                    class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                    aria-label="Edit">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                        <path stroke-linecap="round" stroke-linejoin="round"
                                                            d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                                                    </svg>
                                                </a>
                                                <!-- pour la redirection -->

                                                <button onclick="document.getElementById('myModal').showModal()" id="btn"
                                                    value="<?= $this->datacrypt($values['article_id']) ?>"
                                                    class="supprimerArt flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                                                    aria-label="Delete">
                                                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                                        <path fill-rule="evenodd"
                                                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                            clip-rule="evenodd"></path>
                                                    </svg>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>


                        <div
                            class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">

                            <dialog id="myModal"
                                class="h-auto w-1/4 md:w-1/2 p-5 dark:bg-gray-800 overflow-hidden  bg-white rounded-md ">

                                <div class="flex flex-col w-full h-auto ">
                                    <!-- Header -->
                                    <div class="flex w-full h-auto justify-between items-center">
                                        <div
                                            class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300 text-center flex  justify-center items-center">
                                            <img src="ressources/images/icons-warning.png" alt=""> <span
                                                class="dark:text-white">Warning</span>
                                        </div>
                                        <div onclick="document.getElementById('myModal').close();"
                                            class="focus:outline-none focus:shadow-outline-gray inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-white hover: hover:text-gray-700 text-white">
                                            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img"
                                                aria-hidden="true">
                                                <path
                                                    d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                                    clip-rule="evenodd" fill-rule="evenodd"></path>
                                            </svg>
                                        </div>
                                        <!--Header End-->
                                    </div>
                                    <!-- Modal Content-->
                                    <div class="text-sm text-center text-gray-700 dark:text-gray-400 ">
                                        <h3 class="mb-2 uppercase">Etes vous sure ?</h3>
                                        <p class="dark:text-gray-700">Vous désirez vraiment supprimer cet article
                                            définitivement ? Vous etes libre, mais retenez tout simplement
                                            que cette action est irréversible
                                        </p>
                                    </div>
                                    <!-- End of Modal Content-->

                                    <footer
                                        class="flex flex-col items-center justify-center px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
                                        <button onclick="document.getElementById('myModal').close();"
                                            class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                                            Annuler
                                        </button>
                                        <button
                                            class="redirect w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-red-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-red-600 hover:bg-rose-700 focus:outline-none focus:shadow-outline-purple">
                                            Supprimer définitivement
                                        </button>
                                    </footer>

                                </div>
                            </dialog>

                        </div>

                        <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150"
                            x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100"
                            x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100"
                            x-transition:leave-end="opacity-0"
                            class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">
                            <!-- Modal -->
                            <div x-show="isModalOpen" x-transition:enter="transition ease-out duration-150"
                                x-transition:enter-start="opacity-0 transform translate-y-1/2"
                                x-transition:enter-end="opacity-100"
                                x-transition:leave="transition ease-in duration-150"
                                x-transition:leave-start="opacity-100"
                                x-transition:leave-end="opacity-0  transform translate-y-1/2" @click.away="closeModal"
                                @keydown.escape="closeModal"
                                class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl"
                                role="dialog" id="modal">
                                <!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
                                <header class="flex justify-end">
                                    <button
                                        class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700"
                                        aria-label="close" @click="closeModal">
                                        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img"
                                            aria-hidden="true">
                                            <path
                                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                                clip-rule="evenodd" fill-rule="evenodd"></path>
                                        </svg>
                                    </button>
                                </header>
                                <!-- Modal body -->
                                <div class="mt-4 mb-6">
                                    <!-- Modal title -->
                                    <p class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300">
                                    <div class="flex items-center text-sm">
                                        <!-- Avatar with inset shadow -->
                                        <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                            <img class="object-cover w-full h-full rounded-full"
                                                src="/ressources/images/account.png" alt="" loading="lazy" />
                                            <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true">
                                            </div>
                                        </div>
                                        <div>
                                            <p class="user_name font-semibold  dark:text-white pb-2">
                                            </p>
                                            <span
                                                class="user_email px-2 py-1 font-semibold leading-tight text-yellow-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                            </span>
                                        </div>
                                    </div>
                                    </p>
                                    <p class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300">
                                    <div class="flex items-center text-sm">
                                        <!-- Avatar with inset shadow -->
                                        <div id="messages"
                                            class="flex flex-col space-y-4 p-3 overflow-y-auto scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
                                            <div class="chat-message">
                                                <div class="flex items-end">
                                                    <div
                                                        class="flex flex-col space-y-2 text-xs max-w-xs mx-2 order-2 items-start">
                                                        <div><span
                                                                class="user_text px-4 py-2 rounded-lg inline-block rounded-bl-none bg-gray-300 text-gray-600 dark:text-white"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </p>
                                </div>
                                <form>
                                    <input type="hidden" id="id" name="id">
                                    <input type="hidden" id="email" name="email">
                                    <div class="flex items-center py-2 px-3 bg-gray-50 rounded-lg dark:bg-gray-700">
                                        <textarea id="sujet" rows="1"
                                            class="py-4 px-2 block mx-4 p-2.5 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                            placeholder="Objet..."></textarea>
                                    </div>
                                    <div class="flex items-center py-2 px-3 bg-gray-50 rounded-lg dark:bg-gray-700">
                                        <textarea id="chat" rows="1"
                                            class="py-4 px-2 block mx-4 p-2.5 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                            placeholder="Message..."></textarea>
                                        <button type="submit" id="submitVal"
                                            class="inline-flex justify-center p-2 text-blue-600 rounded-full cursor-pointer hover:bg-blue-100 dark:text-blue-500 dark:hover:bg-gray-600">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                    d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                            </svg>
                                        </button>
                                    </div>
                                </form>
                                <!-- </footer> -->
                            </div>
                        </div>

                        <div style="display: none;"
                            class="elem fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">

                            <!-- Modal -->
                            <div class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl"
                                role="dialog">
                                <!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
                                <header class="flex justify-end">
                                    <button
                                        class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700 fermer"
                                        aria-label="close" @click="closeModal">
                                        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img"
                                            aria-hidden="true">
                                            <path
                                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                                clip-rule="evenodd" fill-rule="evenodd"></path>
                                        </svg>
                                    </button>
                                </header>
                                <!-- Modal body -->
                                <div class="mt-4 mb-6">
                                    <!-- Modal title -->
                                    <p class="mb-4 text-lg font-semibold text-gray-700 dark:text-gray-300">
                                        Modifier cette catgorie
                                    </p>
                                    <!-- Modal description -->
                                    <div class="text-sm text-gray-700 dark:text-gray-400">
                                        <h3 class="mb-2">Nom de la catégorie</h3>

                                        <input
                                            class=" block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input"
                                            placeholder="Entrer la catégorie dans ce champ" id="category_names" />

                                        <input
                                            class="block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input"
                                            id="category_id" type="hidden" />

                                        <input
                                            class="block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input"
                                            id="category_img" type="hidden" />

                                        <div class="mt-2 py-4 flex items-center justify-center w-full">
                                            <label for="dropzone-files"
                                                class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                                                <div class="flex flex-col py-2 items-center justify-center pt-5 pb-6">
                                                    <svg class="w-5 h-5 mb-2 text-gray-400" fill="none"
                                                        stroke="currentColor" viewBox="0 0 24 24"
                                                        xmlns="http://www.w3.org/2000/svg">
                                                        <path stroke-linecap="round" stroke-linejoin="round"
                                                            stroke-width="2"
                                                            d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12">
                                                        </path>
                                                    </svg>
                                                    <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span
                                                            class="font-semibold">Télecharger une image</span> ou faire
                                                        un drag and drop</p>
                                                    <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or
                                                        GIF (MAX. 2MB)</p>
                                                </div>
                                                <input id="dropzone-files" type="file" class="hidden" />
                                            </label>
                                        </div>

                                        <input
                                            class="mt-2 py-2 w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input"
                                            type="text" placeholder="Une petite description" aria-label="Search"
                                            id="category_descriptions" />
                                    </div>
                                </div>
                                <footer
                                    class="flex flex-col items-center justify-end px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
                                    <button @click="closeModal"
                                        class="closeFermer w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                                        Annuler
                                    </button>
                                    <button
                                        class="redirect w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
                                        id="modifer">
                                        Modifier
                                    </button>
                                </footer>
                            </div>
                        </div>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/ressources/js/categoryNew.js"></script>
<script src="/ressources/js/article_js.js"></script>
<script src="/ressources/js/sms.js"></script>