<footer class="binduz-er-footer-2-area">
    <div class="bg-footer">
        <div class=" container">
            <div class="row">
                <div class=" col-lg-12">
                    <div class="binduz-er-footer-box">
                        <div class="row">
                            <div class=" col-lg-4">
                                <div class="binduz-er-footer-about text-center">
                                    <div class="binduz-er-logo">
                                        <a href="#"><img src="/ressources/images/logo-4.png" alt="logo"></a>
                                    </div>
                                    <p>MasterCode est un blog basé sur l'apprentissage de certains langages de
                                        programmations.</p>
                                </div>
                            </div>
                            <div class=" col-lg-4">
                                <div class="binduz-er-footer-gallery ml-50">
                                    <div class="binduz-er-footer-title">
                                        <h4 class="binduz-er-title">Quelques Catégories</h4>
                                    </div>
                                    <div class="binduz-er-footer-gallery-widget d-flex">
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/angular.png" alt="">
                                            </a>
                                        </div>
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/js.png" alt="">
                                            </a>
                                        </div>
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/php.png" alt="">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="binduz-er-footer-gallery-widget d-flex">
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/sql.png" alt="">
                                            </a>
                                        </div>
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/css.png" alt="">
                                            </a>
                                        </div>
                                        <div class="binduz-er-item footerImg">
                                            <a href="#">
                                                <img src="/ressources/images/vuejs.png" alt="">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=" col-lg-4">
                                <div class="binduz-er-footer-navigation">
                                    <div class="binduz-er-footer-title">
                                        <h3 class="binduz-er-title">Informations sur MasterCode</h3>
                                    </div>
                                    <div class="binduz-er-footer-list">
                                        <ul>
                                            <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newAbout') ?>">A propos de nous</a></li>
                                            <li><a href="#">Conditions d'utilisation</a></li>
                                            <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newContact') ?>">Contactez-nous</a></li>
                                        </ul>
                                        <ul>
                                            <li><a href="#">Politique de confidentialité</a></li>
                                            <li><a href="#">Archives</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="binduz-er-footer-copyright-area binduz-er-footer-copyright-area-2">
        <div class="bg-foot">
            <div class=" container">
                <div class="binduz-er-footer-copyright-box">
                    <div class="row align-items-center">
                        <div class=" col-lg-6">
                            <div class="binduz-er-copyright-text">
                                <p>Copyright By@<span>MasterCode</span> - 2023</p>
                            </div>
                        </div>
                        <div class=" col-lg-6">
                            <div class="binduz-er-copyright-menu float-lg-end float-none">
                                <ul>
                                    <li><a href="#">Politique de confidentialité</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<?php require_once("../App/Views/getAdressIp.phtml"); ?>

<script src="/ressources/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="/ressources/js/vendor/jquery-1.12.4.min.js"></script>

<script src="/ressources/js/bootstrap.min.js"></script>
<script src="/ressources/js/popper.min.js"></script>

<script src="/ressources/js/slick.min.js"></script>

<script src="/ressources/js/jquery.nice-select.min.js"></script>

<script src="/ressources/js/isotope.pkgd.min.js"></script>

<script src="/ressources/js/imagesloaded.pkgd.min.js"></script>

<script src="/ressources/js/jquery.magnific-popup.min.js"></script>

<script src="/ressources/js/main.js"></script>

</body>

</html>