<?php @session_start(); ?>

<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>MasterCode</title>

    <link rel="shortcut icon" href="/ressources/images/web.svg" />

    <link rel="stylesheet" href="/ressources/css/bootstrap.min.css">

    <link rel="stylesheet" href="/ressources/css/font-awesome.min.css">

    <link rel="stylesheet" href="/ressources/css/nice-select.css">

    <link rel="stylesheet" href="/ressources/css/magnific-popup.css">

    <link rel="stylesheet" href="/ressources/css/slick.css">

    <link rel="stylesheet" href="/ressources/css/default.css">

    <link rel="stylesheet" href="/ressources/css/style.css">


</head>

<body class="gray-bg">

    <div class="binduz-er-news-off_canvars_overlay"></div>
    <div class="binduz-er-news-offcanvas_menu binduz-er-news-offcanvas_menu_left">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="binduz-er-news-offcanvas_menu_wrapper">
                        <div class="binduz-er-news-canvas_close">
                            <a href="javascript:void(0)"><i class="fal fa-times"></i></a>
                        </div>
                        <?php if (isset($_SESSION['Auth'])): ?>
                            <div class="accountHeader" style="background-color: <?= $_SESSION["Auth"]["bgc"] ?>;">
                                <?php $pseudo = $_SESSION['Auth']['pseudo']; echo $pseudo[0]; ?>
                            </div>
                        <?php endif; ?>
                        <div id="menu" class="text-left ">
                            <ul class="binduz-er-news-offcanvas_main_menu">
                                <?php if (isset($_SESSION['Auth'])): ?>
                                    <li class="binduz-er-news-menu-item-has-children binduz-er-news-active">
                                        <a href="#"><?= $_SESSION['Auth']['pseudo'] ?></a>
                                        <ul class="binduz-er-news-sub-menu">
                                            <?php if (isset($_SESSION['Auth']['role']) && $_SESSION['Auth']['role'] !== '1'): ?>
                                                <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('dash') ?>">Dashboard</a></li>
                                            <?php endif; ?>
                                            <li><a href="#">Commentaires</a></li>
                                            <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newLogout') ?>">Se déconnecter</a></li>
                                        </ul>
                                    </li>
                                <?php endif; ?>
                                <li class="binduz-er-news-menu-item-has-children binduz-er-news-active">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">Accueil</a>
                                </li>
                                <li class="binduz-er-news-menu-item-has-children">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newArticles') ?>">Découvrir
                                        nos articles</a>
                                </li>
                                <li class="binduz-er-news-menu-item-has-children binduz-er-news-active">
                                    <a href="#">Nos catégories</a>
                                    <ul class="binduz-er-news-sub-menu">
                                        <li><a href="#">HTML</a></li>
                                        <li><a href="#">CSS</a></li>
                                        <li><a href="#">JavaScript</a></li>
                                        <li><a href="#">PHP</a></li>
                                        <li><a href="#">SQL</a></li>
                                        <li><a href="#">VueJS</a></li>
                                        <li><a href="#">React JS</a></li>
                                        <li><a href="#">Angular JS</a></li>
                                        <li><a href="#">JQuery</a></li>
                                        <li><a href="#">Java</a></li>
                                    </ul>
                                </li>
                                <li class="binduz-er-news-menu-item-has-children">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newAbout') ?>">A
                                        propos de nous</a>
                                </li>
                                <li class="binduz-er-news-menu-item-has-children">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newContact') ?>">Contactez-nous</a>
                                </li>
                                <?php if (!isset($_SESSION['Auth'])): ?>
                                    <li class="binduz-er-news-menu-item-has-children">
                                        <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newViewLogin') ?>"> Se connecter</a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </div>
                        <div class="binduz-er-news-offcanvas_footer">
                            <div class="binduz-er-news-logo text-center mb-30 mt-30">
                                <a href="index.html">
                                    <img src="/ressources/images/logo.png" alt="logo du site">
                                </a>
                            </div>
                            <p>MasterCode est un blog basé sur l'apprentissage de certains langages de programmations.
                            </p>
                            <ul>
                                <li><i class="fas fa-phone"></i> +XXX XX XX XX XX</li>
                                <li><i class="fas fa-envelope"></i> mastercode@gmail.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="binduz-er-news-search-box">
        <div class="binduz-er-news-search-header">
            <div class=" container mt-60">
                <div class="row">
                    <div class=" col-6">
                        <img src="/ressources/images/logo-4.png" alt="logo du site"> <!-- search title -->
                    </div>
                    <div class=" col-6">
                        <div class="binduz-er-news-search-close float-end">
                            <button class="binduz-er-news-search-close-btn flexSearch">Fermer <i
                                    class="fal fa-times"></i> </button>
                        </div> <!-- search close -->
                    </div>
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- search header -->
        <div class="binduz-er-news-search-body">
            <div class=" container">
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="binduz-er-news-search-form">
                            <form action="#">
                                <input type="text" placeholder="Rechercher un article" list="article">
                                <datalist id="article">
                                    <option value="Article1">Article1</option>
                                    <option value="Article2">Article2</option>
                                    <option value="Article3">Article3</option>
                                </datalist>
                                <button><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div> <!-- row -->
            </div> <!-- container -->
        </div> <!-- search body -->
    </div>

    <header class="binduz-er-news-top-header-area-2 bg_cover">
        <div class=" container">
            <div class="headerElement">
                <div class="">
                    <div class="binduz-er-news-top-header-btns">
                        <ul>
                            <li>
                                <span class="binduz-er-toggle-btn binduz-er-news-canvas_open"><i
                                        class="fal fa-bars"></i> Menu</span>
                            </li>
                            <li>
                                <a class="binduz-er-news-search-open" href="#"><i class="fal fa-search"></i>
                                    Recherche</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="navigation">
                    <nav class="navbar navbar-expand-lg">
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul class="navbar-nav nav-element mr-auto">
                                <li class="nav-link-element actived">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">Accueil</a>
                                </li>
                                <li class="nav-link-element">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newArticles') ?>">Découvrir
                                        nos articles</a>
                                </li>
                                <li class="nav-link-element">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newAbout') ?>">A
                                        propos de nous</a>
                                </li>
                                <li class="nav-link-element">
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newContact') ?>">Contactez-nous</a>
                                </li>
                            </ul>
                        </div> <!-- navbar collapse -->
                    </nav>
                </div>
                <div class="">
                    <div class="binduz-er-news-top-header-weather">
                        <ul>
                            <?php if (!isset($_SESSION['Auth'])): ?>
                                <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newViewLogin') ?>"><i class="fal fa-user"></i> Se connecter</a></li>
                            <?php else: ?>
                                <li><a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newLogout') ?>">Se déconnecter</a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="topBody">
        <a href="#top"><i class="fas fa-arrow-up"></i></a>
    </div>