
<?php require_once("../App/Views/getAdressIp.phtml"); ?>

<script src="/ressources/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="/ressources/js/vendor/jquery-1.12.4.min.js"></script>

<script src="/ressources/js/bootstrap.min.js"></script>
<script src="/ressources/js/popper.min.js"></script>

<script src="/ressources/js/slick.min.js"></script>

<script src="/ressources/js/jquery.nice-select.min.js"></script>

<script src="/ressources/js/isotope.pkgd.min.js"></script>

<script src="/ressources/js/imagesloaded.pkgd.min.js"></script>

<script src="/ressources/js/jquery.magnific-popup.min.js"></script>

<script src="/ressources/js/main.js"></script>

</body>

</html>