<div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">

        <div class="text-sm text-gray-700 dark:text-gray-400">
            <select name="categorie" id="categorie" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut">Choisir un utilisateur</option>
                <?php foreach ($allUsers as $key => $values) : ?>
                    <option value=<?= $values["user_pseudo"] ?>> <?= $values["user_pseudo"] ?>

                    </option>
                <?php endforeach; ?>
            </select>
            <input class="mt-6 block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input dark:border-green-200" placeholder="Poste actuelle" />

            <!-- name=poste , id=post => unused -->
            <select name="poste" id="poste" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut">Choisir un nouveau role pour cet utiisateur</option>
                <?php foreach ($allUsers as $key => $values) : ?>
                    <option value=<?= $values["user_pseudo"] ?>> <?= $values["user_pseudo"] ?>

                    </option>
                <?php endforeach; ?>
            </select>
            <button class="mt-4 w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                Valider
            </button>
        </div>

    </div>