<div class="w-full overflow-hidden rounded-lg shadow-xs">
    <!-- <div class="h-screen w-screen bg-gradient-to-br from-slate-100 to-slate-300 py-32"> -->
        <div class="bg-white/60 backdrop-blur-xl z-20 max-w-md absolute right-5 top-5 rounded-lg p-6 shadow">
            <h1 class="text-xl text-slate-700 font-medium">Welcome back, Eduard 👋</h1>
            <div class="flex justify-between items-center">
                <a href="#" class="text-slate-500 hover:text-slate-700 text-sm inline-flex space-x-1 items-center">
                    <span>Go to Dashboard</span>
                    <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
                    </svg>
                </a>

            </div>
        </div>
    <!-- </div> -->
    <div class="w-full overflow-x-auto">
        <div class="text-sm text-gray-700 dark:text-gray-400">
            <select id="allUsers" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut" selected disabled>Choisir un utilisateur</option>
                <?php foreach ($allUsers as $key => $values): ?>
                    <?php if ($values["user_pseudo"] !== "SuperAdmin"): ?>
                        <option value=<?= $this->datacrypt($values["user_id"]) ?>> <?= $values["user_pseudo"] ?>
                        </option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
            <input class="post mt-6 block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input dark:border-green-200" placeholder="Poste actuelle" />

            <!-- name=poste , id=post => unused -->
            <select name="poste" id="poste" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut" selected disabled>Choisir un nouveau role pour cet utiisateur</option>
                <option value="0">Administrateur</option>
                <option value="1">Utilisateur</option>
                <option value="2">Rédacteur</option>
            </select>
            <button class="update mt-4 w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                Valider
            </button>
        </div>

    </div>