<div class="w-full overflow-hidden rounded-lg shadow-xs">
    <!-- <div class="h-screen w-screen bg-gradient-to-br from-slate-100 to-slate-300 py-32"> -->

    <div class='m-12 space-y-6'>
        <div class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3" role="alert">
          
                <span class="flex font-bold text-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                    </svg>
                    Affectation effectuée avec succes
                </span>
        </div>
    </div>

    <!-- </div> -->
    <div class="w-full overflow-x-auto">
        <div class="text-sm text-gray-700 dark:text-gray-400">
            <select id="allUsers" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut" selected disabled>Choisir un utilisateur</option>
                <?php foreach ($allUsers as $key => $values) : ?>
                    <?php if ($values["user_pseudo"] !== "SuperAdmin") : ?>
                        <option value=<?= $this->datacrypt($values["user_id"]) ?>> <?= $values["user_pseudo"] ?>
                        </option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
            <input class="post mt-6 block w-full mt-1 text-sm border-green-600 dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input dark:border-green-200" placeholder="Poste actuelle" />

            <!-- name=poste , id=post => unused -->
            <select name="poste" id="poste" class="mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <option value="defaut" selected disabled>Choisir un nouveau role pour cet utiisateur</option>
                <option value="0">Administrateur</option>
                <option value="1">Utilisateur</option>
                <option value="2">Rédacteur</option>
            </select>
            <button class="update mt-4 w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                Valider
            </button>
        </div>

    </div>