<form method="post">
    <?php if (isset($_SESSION["Auth"])): ?>
        <?php if ($_SESSION["Auth"]["role"] === '0'): ?>
            <select name="etat" id="etat"
                class="py-4 mt-4 block w-full mt-1 text-sm dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                <?php if ($oneArticle[0]['state'] === "attente"): ?>
                    <option value="attente" selected>En attente</option>
                    <option value="publier">Publier l'article</option>
                <?php else: ?>
                    <option value="attente">En attente</option>
                    <option value="publier" selected>Publier l'article</option>
                <?php endif; ?>
            </select>
        <?php else: ?>
            <?php if(isset($_GET["state"])) : ?>
            <input name="etat" id="etat" type="hidden" value="<?= $this->datadecrypt($_GET["state"]) ?>">
        <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>

    <input
        class="py-4 mt-4 mb-4 block w-full mt-1 text-sm border-black dark:border-white dark:text-gray-300 dark:bg-gray-700 focus:border-red-400 focus:outline-none focus:shadow-outline-red form-input dark:border-green-200"
        placeholder="Titre de l'article" id="title" value="<?= $oneArticle[0]['article_title'] ?>" />

    <textarea id="mytextarea"><?= $oneArticle[0]['code_html'] ?></textarea>

    <div class="mt-2 py-4 flex items-center justify-center w-full">
        <label for="dropzone-file"
            class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
            <div class="flex flex-col py-4 items-center justify-center pt-5 pb-6">
                <svg class="w-5 h-5 mb-2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12">
                    </path>
                </svg>
                <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Télecharger une
                        image</span> ou faire un drag and drop</p>
                <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF (MAX. 2MB)</p>
            </div>
            <input id="dropzone-file" type="file" class="hidden" />
        </label>
        <input id="name-file" type="hidden" value="<?= $oneArticle[0]['article_image'] ?>" />
    </div>
    <button value="<?= $this->datacrypt($oneArticle[0]['article_id']) ?>"
        class="mt-4 w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        id="modifier">
        Modifier
    </button>

</form>