<div class="w-full overflow-hidden rounded-lg shadow-xs">
	<div class="w-full overflow-x-auto">
		<table class="w-full whitespace-no-wrap overflow-scroll">
			<thead>
				<tr
					class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
					<th class="px-4 py-3">Nom de l'utilisateur</th>
					<th class="px-4 py-3">Role</th>
					<th class="px-4 py-3">Date de création du compte</th>
					<th class="px-4 py-3">Derniere modification</th>
					<th class="px-4 py-3">Actions</th>
					<!-- <th class="px-4 py-3">Cocher</th> -->
				</tr>
			</thead>
			<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
				<?php foreach ($allUsers as $key => $values): ?>
					<tr class="text-gray-700 dark:text-gray-400">
						<td class="px-4 py-3">
							<div class="flex items-center text-sm">
								<!-- Avatar with inset shadow -->
								<div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
									<img class="object-cover w-full h-full rounded-full"
										src="/ressources/images/web-developer.jpg" alt="" loading="lazy" />
									<div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
								</div>
								<div>
									<p class="font-semibold">
										<?= $values["user_pseudo"] ?>
									</p>

								</div>
							</div>
						</td>
						<td class="px-4 py-3 text-sm">
							<?php if ($values["user_role"] == 0): ?>
								<span
									class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:bg-orange-700 dark:text-orange-700">
									Administrateur
								</span>
							<?php elseif ($values["user_role"] == 1): ?>
								<span
									class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-white">
									Lecteur
								</span>
							<?php else: ?>
								<span
									class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-white">
									Rédacteur
								</span>
							<?php endif; ?>
						</td>
						<td class="px-4 py-3 text-xs">
							<span
								class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
								<?= $values["created_at"] ?>
							</span>
						</td>
						<td class="px-4 py-3 text-sm">
							<?php if ($values["updated_at"] == null): ?>
								<span
									class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-full dark:bg-yellow-700 dark:text-yellow-100">
									---
								</span>
							<?php else: ?>
								<?php if ($values["user_role"] == 0): ?>
									<span
										class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
										Le
										<?= $values["updated_at"] ?> en compte Adminstrateur
									</span>
								<?php elseif ($values["user_role"] == 1): ?>
									<span
										class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
										Le
										<?= $values["updated_at"] ?> en compte Utilisateur
									</span>

								<?php else: ?>
									<span
										class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
										Le
										<?= $values["updated_at"] ?> en compte Rédacteur
									</span>
								<?php endif; ?>
							<?php endif; ?>

						</td>

						<td class="px-4 py-3">
							<?php if ($values["user_pseudo"] !== "SuperAdmin"): ?>
								<div class="flex items-center space-x-4 text-sm">
									<button
										class="supprime flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
										value="<?= $this->datacrypt($values["user_id"]) ?>" aria-label="Delete">
										<svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
											<path fill-rule="evenodd"
												d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
												clip-rule="evenodd"></path>
										</svg>
									</button>
								</div>
							<?php endif; ?>
						</td>
					</tr>

				<?php endforeach; ?>
				</tr>

			</tbody>
		</table>
	</div>
	<div
		class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
		<span class="flex items-center col-span-3">
		</span>
		<span class="col-span-2"></span>
		<!-- Pagination -->
	
	</div>
</div>