<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main class="mainAbout">
<section class="binduz-er-about-us-area pb-60">
        <div class=" container">
            <div class="row">
                <div class=" col-lg-12">
                    <div class="binduz-er-about-us-thumb aboutImage">
                        <img src="/ressources/images/dev.jpg" alt="developer">
                    </div>
                </div>
                <div class=" col-lg-6">
                    <div class="binduz-er-about-us-content">
                        <h4 class="binduz-er-title">A propos de nous</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio, minima nostrum voluptatibus aperiam necessitatibus, iusto blanditiis laboriosam facilis et sed voluptatum corporis eaque autem pariatur illo modi! Sapiente libero ab consequatur optio assumenda id, dolores, facilis quisquam earum quis quam asperiores voluptate cupiditate eum quasi, nam iusto commodi minima dignissimos?</p>
                    </div>
                </div>
                <div class=" col-lg-6">
                    <div class="binduz-er-about-us-content">
                        <h4 class="binduz-er-title">Mission & Vision</h4>
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi quibusdam impedit excepturi aspernatur eos. Dolor necessitatibus nesciunt iure nobis a molestias dolore architecto minima, sed consequuntur iste voluptatum corrupti magni vitae ducimus recusandae illum non commodi quasi accusantium nisi. Odio eius eaque consequuntur placeat molestias cupiditate unde, dicta ipsum omnis.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class=" col-lg-3 col-md-6">
                    <div class="binduz-er-about-us-box">
                        <div class="binduz-er-icon">
                            <img src="assets/images/icon/1.png" alt="">
                        </div>
                        <h4 class="binduz-er-title">Nos liens</h4>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-6">
                    <div class="binduz-er-about-us-box">
                        <div class="binduz-er-icon">
                            <img src="assets/images/icon/2.png" alt="">
                        </div>
                        <h4 class="binduz-er-title">Nos liens</h4>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-6">
                    <div class="binduz-er-about-us-box">
                        <div class="binduz-er-icon">
                            <img src="assets/images/icon/3.png" alt="">
                        </div>
                        <h4 class="binduz-er-title">Nos liens</h4>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-6">
                    <div class="binduz-er-about-us-box">
                        <div class="binduz-er-icon">
                            <img src="assets/images/icon/4.png" alt="">
                        </div>
                        <h4 class="binduz-er-title">Nos liens</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>

<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>