<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-author-item-area pb-20">
        <div class="binduz-er-blog-bg-area"
            style="background-image: url(/ressources/images/images_principales/<?= $oneArticle[0]["article_image"] ?>);">
        </div>
        <div class=" container">
            <div class="row">
                <div class=" col-lg-9">
                    <div class="binduz-er-author-item mb-40 mtop-90">
                        <div class="binduz-er-content">
                            <h3 class="binduz-er-title">
                                <?= $oneArticle[0]["article_title"] ?>
                            </h3>
                        </div>
                        <div class="row">

                            <div>
                                <div class="binduz-er-blog-details-box">
                                    <div class="binduz-er-text">
                                        <?= $oneArticle[0]["code_html"] ?>
                                    </div>
                                    <div class="elementArticle">
                                        <div class="iconArticle">
                                            <i class="fal fa-eye"></i>
                                            <?php if (count($oneView) > 0): ?>
                                                <span>
                                                    <?= $oneView[0]["nombre"] ?> vue(s)
                                                </span>
                                            <?php else: ?>
                                                <span>0 vue(s)</span>
                                            <?php endif; ?>
                                        </div>
                                        <div class="iconArticle redHeart">
                                            <form>
                                                <button class="like"
                                                    value="<?= (isset($_SESSION['Auth'])) ? $_SESSION['Auth']['id'] : '' ?>"><i
                                                        class="fal fa-heart"></i></button>
                                            </form>
                                            <?php if ($onelike === false): ?>
                                                    <span id="numLike">0 like(s)</span>
                                                <?php else: ?>
                                                    <span id="numLike">
                                                        <?= $onelike["Nombre"] ?> like(s)
                                                    </span>
                                                <?php endif; ?>
                                        </div>
                                        <div class="iconArticle skyComment">
                                            <a href="#commentForm"><i class="fal fa-comments"></i>
                                                <?php if (count($oneCom) > 0): ?>
                                                    <span id="numCom">
                                                        <?= count($oneCom) ?> posts
                                                    </span>
                                                <?php else: ?>
                                                    <span id="numCom">0 posts</span>
                                                <?php endif; ?>
                                            </a>
                                        </div>
                                    </div>

                                    <div class="binduz-er-footer-add-item bg-prog">
                                    </div>
                                    <?php if (!isset($_SESSION["Auth"])): ?>
                                        <div class="binduz-er-blog-post-newsletter">
                                            <div
                                                class="binduz-er-populer-news-sidebar-newsletter author-page-newsletter mt-40">
                                                <div class="binduz-er-newsletter-box text-center">
                                                    <img src="/ressources/images/icon/icon-4.png" alt="logo du site">
                                                    <h3 class="title-h3">Si cet article vous a plu, inscrivez-vous
                                                        sur le site😉. Merci d'avance.</h3>
                                                    <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newViewLogin') ?>" class="clrArticle">inscrivez-vous <i
                                                            class="fal fa-long-arrow-right"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>

                                    <form action="#" method="post" id="commentForm" class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Laisser un commentaire</h3>
                                        </div>
                                        <div class="row">
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box commentArticle">
                                                    <textarea name="commentPost" id="commentPost" cols="30" rows="10"
                                                        placeholder="Laissez un commentaire"></textarea>
                                                </div>
                                            </div>
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box text-end mt-15">
                                                    <?php if (isset($_SESSION["Auth"])): ?>
                                                        <button type="button" id="sendComment"
                                                            class="binduz-er-main-btn">Postez votre commentaire</button>
                                                    <?php else: ?>
                                                        <button type="button" id="notConnect"
                                                            class="binduz-er-main-btn">Postez votre commentaire</button>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <article class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Voir les commentaires</h3>
                                        </div>
                                        <div class="row overPost">
                                            <?php if (count($oneCom) > 0): ?>
                                                <?php foreach ($oneCom as $key => $values): ?>
                                                    <div class="parentComment" id="<?= "post" . $values['comment_id'] ?>">
                                                        <div class="binduz-er-input-box commentPost"
                                                            style="background-color: <?= $values['user_bgc'] ?>">
                                                            <?php $string = $values["user_pseudo"];
                                                            echo $string[0]; ?>
                                                        </div>
                                                        <div class="bodyPost">
                                                            <div class="childPost">
                                                                <h4>
                                                                    <?= $values['user_pseudo'] ?>
                                                                </h4>
                                                                <form class="formUpd">
                                                                    <textarea name="zonetext" id="zonetext" cols="30" rows="10"></textarea>
                                                                </form>
                                                                <p>
                                                                    <?= $values['comment_body'] ?>
                                                                </p>
                                                                <span><i class="fal fa-calendar-alt"></i>
                                                                    <?= $values['created_at'] ?>
                                                                </span>
                                                                <?php if (isset($_SESSION["Auth"])): ?>
                                                                    <div class="formUp">
                                                                        <?php if ($_SESSION["Auth"]["pseudo"] !== $values["user_pseudo"]): ?>
                                                                            <a href="#commentForm" class="answer">Répondre</a>
                                                                        <?php endif; ?>
                                                                        <form action="#" class="upDelForm">
                                                                            <input type="hidden"
                                                                                value="<?= $this->datadecrypt($values['comment_id']) ?>"
                                                                                id="user_id_comment">
                                                                            <?php if ($_SESSION["Auth"]["pseudo"] === $values["user_pseudo"]): ?>
                                                                                <button class="upCom"><i class="fal fa-pencil"></i>
                                                                                    Modifier</button>
                                                                                <button class="upPost"
                                                                                    value="<?= $this->datacrypt($values['comment_id']) ?>"><i
                                                                                        class="fal fa-pencil"></i> Modifier</button>
                                                                                <button class="del"
                                                                                    value="<?= $this->datacrypt($values['comment_id']) ?>"><i
                                                                                        class="fal fa-ban"></i>
                                                                                    Supprimer</span></button>
                                                                            <?php endif; ?>
                                                                            <?php if (isset($_SESSION['Auth']['role']) && $_SESSION['Auth']['role'] == '0'): ?>
                                                                                <?php if ($_SESSION['Auth']['pseudo'] !== $values['user_pseudo']): ?>
                                                                                    <button class="delPost"
                                                                                        value="<?= $this->datacrypt($values['comment_id']) ?>"><i
                                                                                            class="fal fa-ban"></i> Supprimer ce
                                                                                        post</span></button>
                                                                                <?php endif; ?>
                                                                            <?php endif; ?>
                                                                        </form>
                                                                    </div>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3">
                    <div class="binduz-er-populer-news-sidebar">

                        <article
                            class="binduz-er-populer-news-sidebar-newsletter binduz-er-author-page-newsletter mt-40">
                            <div class="binduz-er-newsletter-box text-center">
                                <img src="/ressources/images/icon/icon-3.png" alt="logo du site">
                                <h3 class="binduz-er-title">MasterCode & Opportunités</h3>
                                <p>Chers visiteurs, pour ceux qui sont intéressés....</p>
                                <a class="clrBtn">Allez sur <i class="fal fa-long-arrow-right"></i></a>
                            </div>
                        </article>

                        <div class="binduz-er-populer-news-sidebar-post pt-60">
                            <div class="binduz-er-popular-news-title">
                                <ul class="nav nav-pills mb-3" id="pills-tab-2" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill"
                                            href="#pills-home" role="tab" aria-controls="pills-home"
                                            aria-selected="true">Les publicités de Google Ads</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-content" id="pills-tabContent-2">
                                <div class="tab-pane fade show active" id="pills-home" role="tabpanel"
                                    aria-labelledby="pills-home-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="pills-profile" role="tabpanel"
                                    aria-labelledby="pills-profile-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <article class="binduz-er-populer-news-social binduz-er-author-page-social mt-40">
                            <div class="binduz-er-popular-news-title">
                                <h3 class="binduz-er-title">Publicités google ads</h3>
                            </div>
                        </article>

                    </div>
                </div>
            </div>
        </div>
    </section>


</main>
<?php if (isset($_SESSION["Auth"])): ?>
    <script src="/ressources/js/articleOne.js"></script>
<?php else: ?>
    <script src="/ressources/js/notConnect.js"></script>
<?php endif; ?>
<?php include_once("../App/Views/getViewArticle.phtml") ?>
<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>