<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-author-item-area pb-20">
        <div class="binduz-er-blog-bg-area"></div>
        <div class=" container">
            <div class="row">
                <div class=" col-lg-9">
                    <div class="binduz-er-author-item mb-40 mtop-90">
                        <div class="binduz-er-content">
                            <div class="binduz-er-meta-item">
                                <div class="binduz-er-meta-categories">
                                    <a href="#">JavaScript</a>
                                </div>
                                <div class="binduz-er-meta-date">
                                    <span><i class="fal fa-calendar-alt"></i>2023-05-25</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class=" col-lg-2">
                                <div class="binduz-er-blog-social-share">
                                    <div class="binduz-er-item mb-10">
                                        <span class="iconArticle" href="#">
                                            <i class="fal fa-user"></i>
                                            <span>Par Kola</span>
                                        </span>
                                    </div>
                                    <div class="binduz-er-item mb-10">
                                        <span class="iconArticle" href="#">
                                            <i class="fal fa-eye"></i>
                                            <span>5k</span>
                                        </span>
                                    </div>
                                    <div class="binduz-er-item mb-10">
                                        <span class="iconArticle redHeart" href="#">
                                            <i class="fal fa-heart"></i>
                                            <span>5k</span>
                                        </span>
                                    </div>
                                    <div class="binduz-er-item mb-10">
                                        <span class="iconArticle skyComment" href="#">
                                            <i class="fal fa-comments"></i>
                                            <span>5k</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class=" col-lg-10">
                                <div class="binduz-er-blog-details-box">
                                    <div class="binduz-er-text">
                                        Code html
                                        <h2><span style="font-size: 24px; font-family: Arial, Helvetica, sans-serif; color: rgb(26, 188, 156);">testy</span></h2><p><br></p><p>sfsdfsdfsd</p><p>jlhkhjkgjkgkj tjghjghj</p>
                                    </div>

                                    <div class="binduz-er-footer-add-item text-center pt-55">
                                        <span class="binduz-er-mb-10 d-inline-block">ADVERTISEMENT</span>
                                        <img src="assets/images/space-bg-4.jpg" alt="">
                                    </div>

                                    <div class="binduz-er-blog-post-newsletter">
                                        <div
                                            class="binduz-er-populer-news-sidebar-newsletter author-page-newsletter mt-40">
                                            <div class="binduz-er-newsletter-box text-center">
                                                <img src="/ressources/images/icon/icon-4.png" alt="logo du site">
                                                <h3 class="binduz-er-title">Si cet article vous a plu, inscrivez-vous
                                                    sur le site😉. Merci d'avance.</h3>
                                                <a class="clrArticle">inscrivez-vous <i
                                                        class="fal fa-long-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>

                                    <form action="#" method="post" class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Laisser un commentaire</h3>
                                        </div>
                                        <div class="row">
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box commentArticle">
                                                    <textarea name="commentPost" id="commentPost" cols="30" rows="10"
                                                        placeholder="Saisissez votre commentaire"></textarea>
                                                </div>
                                                <input type="hidden" value="">
                                            </div>
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box text-end mt-15">
                                                    <button type="button" id="sendComment"
                                                        class="binduz-er-main-btn">Postez votre commentaire</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <article class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Voir les commentaires</h3>
                                        </div>
                                        <div class="row">
                                            <div class="parentComment">
                                                <div class="binduz-er-input-box commentPost">
                                                    k
                                                </div>
                                                <div class="bodyPost">
                                                    <h4>Kola</h4>
                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae, consequuntur?</p>
                                                    <p><i class="fal fa-calendar-alt"></i> 2023-05-25</p>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3">
                    <div class="binduz-er-populer-news-sidebar">

                        <article
                            class="binduz-er-populer-news-sidebar-newsletter binduz-er-author-page-newsletter mt-40">
                            <div class="binduz-er-newsletter-box text-center">
                                <img src="/ressources/images/icon/icon-3.png" alt="logo du site">
                                <h3 class="binduz-er-title">MasterCode & Opportunités</h3>
                                <p>Chers visiteurs, pour ceux qui sont intéressés....</p>
                                <a class="clrBtn">Allez sur <i class="fal fa-long-arrow-right"></i></a>
                            </div>
                        </article>

                        <div class="binduz-er-populer-news-sidebar-post pt-60">
                            <div class="binduz-er-popular-news-title">
                                <ul class="nav nav-pills mb-3" id="pills-tab-2" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill"
                                            href="#pills-home" role="tab" aria-controls="pills-home"
                                            aria-selected="true">Les publicités de Google Ads</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-content" id="pills-tabContent-2">
                                <div class="tab-pane fade show active" id="pills-home" role="tabpanel"
                                    aria-labelledby="pills-home-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="pills-profile" role="tabpanel"
                                    aria-labelledby="pills-profile-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <article class="binduz-er-populer-news-social binduz-er-author-page-social mt-40">
                            <div class="binduz-er-popular-news-title">
                                <h3 class="binduz-er-title">Publicités google ads</h3>
                            </div>
                        </article>

                    </div>
                </div>
            </div>
        </div>
    </section>


</main>

<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>