<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-author-item-area pb-20">
        <div class="binduz-er-blog-bg-area" style="background-image: url(/ressources/images/images_principales/<?= $oneArticle[0]["article_image"] ?>);"></div>
        <div class=" container">
            <div class="row">
                <div class=" col-lg-9">
                    <div class="binduz-er-author-item mb-40 mtop-90">
                        <div class="binduz-er-content">
                            <h3 class="binduz-er-title"><?= $oneArticle[0]["article_title"] ?></h3>
                        </div>
                        <div class="row">

                            <div>
                                <div class="binduz-er-blog-details-box">
                                    <div class="binduz-er-text">
                                        <?= $oneArticle[0]["code_html"] ?>
                                    </div>
                                    <div class="elementArticle">
                                        <div class="iconArticle">
                                            <i class="fal fa-eye"></i>
                                            <?php if(count($oneView) > 0) : ?>
                                            <span><?= $oneView[0]["nombre"] ?> vues</span>
                                            <?php else : ?>
                                            <span>0 vues</span>
                                            <?php endif; ?>
                                        </div>
                                        <div class="iconArticle redHeart">
                                            <form action="#">
                                                <input type="hidden" id="user_id" value="">
                                                <button><i class="fal fa-heart"></i></button>
                                            </form>
                                            <span>5k</span>
                                        </div>
                                        <div class="iconArticle skyComment">
                                            <a href="#commentForm"><i class="fal fa-comments"></i></a>
                                            <span>5k</span>
                                        </div>
                                    </div>

                                    <div class="binduz-er-footer-add-item bg-prog">
                                    </div>

                                    <div class="binduz-er-blog-post-newsletter">
                                        <div
                                            class="binduz-er-populer-news-sidebar-newsletter author-page-newsletter mt-40">
                                            <div class="binduz-er-newsletter-box text-center">
                                                <img src="/ressources/images/icon/icon-4.png" alt="logo du site">
                                                <h3 class="binduz-er-title">Si cet article vous a plu, inscrivez-vous
                                                    sur le site😉. Merci d'avance.</h3>
                                                <a class="clrArticle">inscrivez-vous <i
                                                        class="fal fa-long-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>

                                    <form action="#" method="post" id="commentForm" class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Laisser un commentaire</h3>
                                        </div>
                                        <div class="row">
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box commentArticle">
                                                    <textarea name="commentPost" id="commentPost" cols="30" rows="10"
                                                        placeholder="Saisissez votre commentaire"></textarea>
                                                </div>
                                            </div>
                                            <div class=" col-lg-12">
                                                <div class="binduz-er-input-box text-end mt-15">
                                                    <button type="button" id="sendComment"
                                                        class="binduz-er-main-btn">Postez votre commentaire</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <article class="binduz-er-blog-post-form">
                                        <div class="binduz-er-blog-post-title">
                                            <h3 class="binduz-er-title">Voir les commentaires</h3>
                                        </div>
                                        <div class="row overPost">
                                            <div class="parentComment">
                                                <div class="binduz-er-input-box commentPost">
                                                    k
                                                </div>
                                                <div class="bodyPost">
                                                    <div class="childPost">
                                                        <h4>Kola</h4>
                                                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                                                            Molestiae, consequuntur?</p>
                                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-25</span>
                                                    </div>
                                                    <div>
                                                        <a href="#commentForm" class="answer">Répondre</a>
                                                        <form action="#" class="upDelForm">
                                                            <input type="hidden" value="" id="user_id_comment">
                                                            <button><i class="fal fa-pencil"></i> Modifier</button>
                                                            <button><i class="fal fa-ban"></i> Supprimer</span></button>
                                                            <?php if (isset($_SESSION['Auth']['role']) && $_SESSION['Auth']['role'] == '0'): ?>
                                                                <button><i class="fal fa-ban"></i> Supprimer de cet
                                                                    utilisateur</span></button>
                                                            <?php endif; ?>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="parentComment">
                                                <div class="binduz-er-input-box commentPost">
                                                    E
                                                </div>
                                                <div class="bodyPost">
                                                    <div class="childPost">
                                                        <h4>Erik</h4>
                                                        <p>@Marcos @Kola Lorem ipsum dolor sit amet consectetur,
                                                            adipisicing elit.
                                                            Molestiae, consequuntur?</p>
                                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-25</span>
                                                    </div>
                                                    <div>
                                                        <a href="#commentForm" class="answer">Répondre</a>
                                                        <form action="#" class="upDelForm">
                                                            <input type="hidden" value="" id="user_id_del_comment">
                                                            <button><i class="fal fa-pencil"></i> Modifier</button>
                                                            <button><i class="fal fa-ban"></i> Supprimer</span></button>
                                                            <?php if (isset($_SESSION['Auth']['role']) && $_SESSION['Auth']['role'] == '0'): ?>
                                                                <button><i class="fal fa-ban"></i> Supprimer de cet
                                                                    utilisateur</span></button>
                                                            <?php endif; ?>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="parentComment">
                                                <div class="binduz-er-input-box commentPost">
                                                    M
                                                </div>
                                                <div class="bodyPost">
                                                    <div class="childPost">
                                                        <h4>Marcos</h4>
                                                        <p>@Erik Lorem ipsum dolor sit amet consectetur, adipisicing
                                                            elit.
                                                            Molestiae, consequuntur?</p>
                                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-25</span>
                                                    </div>
                                                    <div>
                                                        <a href="#commentForm" class="answer">Répondre</a>
                                                        <form action="#" class="upDelForm">
                                                            <input type="hidden" value="">
                                                            <button><i class="fal fa-pencil"></i> Modifier</button>
                                                            <button><i class="fal fa-ban"></i> Supprimer</span></button>
                                                            <?php if (isset($_SESSION['Auth']['role']) && $_SESSION['Auth']['role'] == '0'): ?>
                                                                <button><i class="fal fa-ban"></i> Supprimer de cet
                                                                    utilisateur</span></button>
                                                            <?php endif; ?>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3">
                    <div class="binduz-er-populer-news-sidebar">

                        <article
                            class="binduz-er-populer-news-sidebar-newsletter binduz-er-author-page-newsletter mt-40">
                            <div class="binduz-er-newsletter-box text-center">
                                <img src="/ressources/images/icon/icon-3.png" alt="logo du site">
                                <h3 class="binduz-er-title">MasterCode & Opportunités</h3>
                                <p>Chers visiteurs, pour ceux qui sont intéressés....</p>
                                <a class="clrBtn">Allez sur <i class="fal fa-long-arrow-right"></i></a>
                            </div>
                        </article>

                        <div class="binduz-er-populer-news-sidebar-post pt-60">
                            <div class="binduz-er-popular-news-title">
                                <ul class="nav nav-pills mb-3" id="pills-tab-2" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill"
                                            href="#pills-home" role="tab" aria-controls="pills-home"
                                            aria-selected="true">Les publicités de Google Ads</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-content" id="pills-tabContent-2">
                                <div class="tab-pane fade show active" id="pills-home" role="tabpanel"
                                    aria-labelledby="pills-home-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="pills-profile" role="tabpanel"
                                    aria-labelledby="pills-profile-tab">
                                    <div class="binduz-er-sidebar-latest-post-box">
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-1.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Why creating inclusive
                                                        classrooms matters</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-2.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Celebrating Asian Pacific
                                                        American art and</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-3.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">From overcoming burnout to
                                                        finding new</a></h4>
                                            </div>
                                        </div>
                                        <div class="binduz-er-sidebar-latest-post-item">
                                            <div class="binduz-er-thumb">
                                                <img src="assets/images/latest-post-4.jpg" alt="latest">
                                            </div>
                                            <div class="binduz-er-content">
                                                <span><i class="fal fa-calendar-alt"></i> 24th February 2020</span>
                                                <h4 class="binduz-er-title"><a href="#">Sparks of inspiration to the new
                                                        trend 2021</a></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <article class="binduz-er-populer-news-social binduz-er-author-page-social mt-40">
                            <div class="binduz-er-popular-news-title">
                                <h3 class="binduz-er-title">Publicités google ads</h3>
                            </div>
                        </article>

                    </div>
                </div>
            </div>
        </div>
    </section>


</main>
<script src="/ressources/js/articleOne.js"></script>
<?php include_once("../App/Views/getViewArticle.phtml") ?>
<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>