<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>
<main>
    <div class="container">
        <section class="binduz-er-editors-pack-white-area mt-80">
            <div class="PostEl">
                <h2 class="h2Post">Vos commentaires</h2>
                <form>
                    <input type="date" name="dtime" id="dtime">
                </form>
            </div>
            <div class="conPost">
                <?php foreach ($allComments as $key => $value): ?>
                    <?php $pseudo = $_SESSION['Auth']['pseudo']; ?>
                    <?php if (preg_match("/$pseudo/i", $value["comment_body"])): ?>
                        <article class="eachPost eachImg">
                            <img src="/ressources/images/images_principales/<?= $value['article_image'] ?>" alt="image">
                            <div>
                                <h3>
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&articleid=<?= $this->datacrypt($value["article_id"]) ?>&action=<?= $this->datacrypt('articleOne') ?>#post<?= $value['comment_id'] ?>">
                                        <?= $value["article_title"] ?>
                                    </a>
                                </h3>
                                <p>Vous avez été <span class="fow-el">targué</span> sur cet article le
                                    <?= $value["created_at"] ?>.
                                </p>
                            </div>
                        </article>
                    <?php else: ?>
                        <article class="eachPost eachImg">
                            <img src="/ressources/images/images_principales/<?= $value['article_image'] ?>" alt="image">
                            <div>
                                <h3>
                                    <a
                                        href="?goto=<?= $this->datacrypt('home') ?>&articleid=<?= $this->datacrypt($value["article_id"]) ?>&action=<?= $this->datacrypt('articleOne') ?>#post<?= $value['comment_id'] ?>">
                                        <?= $value["article_title"] ?>
                                    </a>
                                </h3>
                                <p>Vous avez commenté cet article le
                                    <?= $value["created_at"] ?>.
                                </p>
                            </div>
                        </article>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </section>
    </div>
</main>
<script src="/ressources/js/affComment.js"></script>
<?php include_once("../App/Views/FrontendUser/includes/scriptinc.phtml") ?>