<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-favorites-categories-area mt-30">
        <article class="binduz-er-map-area">
            <div class=" container">
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="binduz-er-map-box">
                            <iframe
                                src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d41305.0575309695!2d90.40505299581727!3d23.78708119002918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1612844343331!5m2!1sen!2sbd"
                                width="100" height="600" style="border:0;" allowfullscreen="" aria-hidden="false"
                                tabindex="0"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </article>

        <article class="binduz-er-contact-us-area">
            <div class=" container">
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="binduz-er-contact-us-box">
                            <form action="#">
                                <div class="binduz-er-contact-title">
                                    <h4 class="binduz-er-title">Contactez-nous</h4>
                                </div>
                                <div class="row">
                                    <div class=" col-lg-4">
                                        <div class="binduz-er-input-box">
                                            <input type="text" name="name" id="name" placeholder="Entrez votre nom au complet">
                                            <i class="fal fa-user"></i>
                                        </div>
                                    </div>
                                    <div class=" col-lg-4">
                                        <div class="binduz-er-input-box">
                                            <input type="email" name="email" id="email" placeholder="Entrez votre adresse électronique">
                                            <i class="fal fa-envelope"></i>
                                        </div>
                                    </div>
                                    <div class=" col-lg-4">
                                        <div class="binduz-er-input-box binduz-er-select-item">
                                            <input type="text" name="subject" id="subject" placeholder="L'objet du message">
                                            <i class="fal fa-arrow-down"></i>
                                        </div>
                                    </div>
                                    <div class=" col-lg-12">
                                        <div class="binduz-er-input-box">
                                            <textarea name="message" id="message" cols="30" rows="10" placeholder="Entrez votre message"></textarea>
                                            <i class="fal fa-pencil"></i>
                                        </div>
                                    </div>
                                </div>
                                <button class="binduz-er-main-btn">Soumettre le formulaire</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>

</main>

<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>