<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-favorites-categories-area mt-30">
        <!-- <article class="binduz-er-map-area">
            <div class=" container">
                 <div class="row">
                    <div class=" col-lg-12">
                        <div class="binduz-er-map-box">
                            <iframe
                                src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d41305.0575309695!2d90.40505299581727!3d23.78708119002918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1612844343331!5m2!1sen!2sbd"
                                width="100" height="600" style="border:0;" allowfullscreen="" aria-hidden="false"
                                tabindex="0"></iframe>
                                <div>
                                    
                                </div>
                        </div>
                    </div>
                </div> 

                <div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </article> -->

        <article class="binduz-er-contact-us-area">
            <div class="containerss">
                <div style="text-align:start">
                    <h2 style="font-size:3rem;">Contactez-nous</h2>
                </div>
                <div class="row">
                    <div class="columnss images">
                        
                    </div>
                    <div class="columnss">
                        <form action="/action_page.php">
                            <label for="fname">Nom</label>
                            <input class="input" type="text" id="fname" name="firstname" placeholder="Nom">
                            <label for="lname">Prénom</label>
                            <input class="input" type="text" id="lname" name="lastname" placeholder="Prénom">
                            <label for="email">Email</label>
                            <input class="input" type="email" id="email" name="email" placeholder="Email">
                            <!-- <input class="select" type="email"  id="email" name="email">    -->
                            
                            <label for="subject">Votre message</label>
                            <textarea id="subject" name="subject" placeholder="Laissez votre message" style="height:170px" class="textarea"></textarea>
                            <input class="input" type="submit" value="Envoyer">
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </section>

</main>

<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>