<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<section class="binduz-er-editors-pack-white-area mt-80">
        <div class=" container">
            <div class="mtop">
                <h2>Vos archives</h2>
                <div class="dataflex">
                    <div class=" col-lg-3 col-md-6">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb">
                                    <img src="ressources/images/js1.jpg" alt="image">
                                </div>
                                <div class="binduz-er-content pd1">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">Technology</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">How we’re helping get vaccines to more people</a></h5>
                                    <div class="binduz-er-meta-author">
                                        <span>By <span>Rosalina D.</span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3 col-md-6">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb">
                                    <img src="ressources/images/js1.jpg" alt="image">
                                </div>
                                <div class="binduz-er-content pd1">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">Technology</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">El productor Peter CottonTale captura el 2020 en</a></h5>
                                    <div class="binduz-er-meta-author">
                                        <span>By <span>Rosalina D.</span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3 col-md-6">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb">
                                    <img src="ressources/images/js1.jpg" alt="image">
                                </div>
                                <div class="binduz-er-content pd1">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">Technology</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">Producer Peter CottonTale captures 2020 in a song</a></h5>
                                    <div class="binduz-er-meta-author">
                                        <span>By <span>Rosalina D.</span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3 col-md-6">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb">
                                    <img src="ressources/images/js1.jpg" alt="image">
                                </div>
                                <div class="binduz-er-content pd1">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">Technology</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">We pack in here just the things to start a News</a></h5>
                                    <div class="binduz-er-meta-author">
                                        <span>By <span>Rosalina D.</span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
