<?php include_once("../App/Views/FrontendUser/includes/header.phtml") ?>

<main>
    <section class="binduz-er-favorites-categories-area mt-30">
        <div class=" container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="binduz-er-favorites-categories-box">
                        <div class="binduz-er-top-news-title">
                            <h3 class="binduz-er-title">Favorites Categories</h3>
                        </div>
                        <div class="binduz-er-favorites-categories-list flexElement">
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/html.png" alt="html">
                                    <span>HTML</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/css.png" alt="">
                                    <span>CSS</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/js.png" alt="">
                                    <span>JavaScript</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/php.png" alt="">
                                    <span>PHP</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/sql.png" alt="">
                                    <span>SQL</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/vuejs.png" alt="">
                                    <span>VueJS</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/react.svg" alt="">
                                    <span>React JS</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/angular.png" alt="">
                                    <span>Angular JS</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/jquery.png" alt="">
                                    <span>JQuery</span>
                                </a>
                            </div>
                            <div class="imageElement binduz-er-item">
                                <a href="#">
                                    <img src="/ressources/images/java.png" alt="">
                                    <span>Java</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="binduz-er-news-slider-area pb-60">
        <div class=" container">
            <div class="binduz-er-news-slider-box">
                <div class="row g-0 align-items-center">
                    <div class=" col-lg-6">
                        <div class="binduz-er-news-slider-item">
                            <div class="binduz-er-item imageDiv">
                                <img src="/ressources/images/javascript1.png" alt="js">
                            </div>
                            <div class="binduz-er-item imageDiv">
                                <img src="/ressources/images/javascript2.jpg" alt="js">
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-6">
                        <div class="binduz-er-news-slider-content-slider">
                            <div class="binduz-er-item">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">JavaScript</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                    </div>
                                </div>
                                <div class="binduz-er-news-slider-content">
                                    <h3 class="binduz-er-title"><a href="#">Qu'est-ce qu'une variable en JavaScript
                                            ?</a></h3>
                                    <p>Un conseil: lisez cet article, vous pourrez en tirer des leçons🧐.</p>
                                </div>
                                <div class="binduz-er-meta-author">
                                    <div class="binduz-er-author accountImg">
                                        <img src="/ressources/images/account.png" alt="image">
                                        <span>Publié par <span>Kola</span></span>
                                    </div>
                                    <div class="binduz-er-meta-list">
                                        <ul>
                                            <li><i class="fal fa-eye"></i> 5k</li>
                                            <li><i class="fal fa-heart"></i> 5k</li>
                                            <li><i class="fal fa-comments"></i> 5k</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="binduz-er-item">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">JavaScript</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                    </div>
                                </div>
                                <div class="binduz-er-news-slider-content">
                                    <h3 class="binduz-er-title"><a href="#">Déclarations en JavaScript</a></h3>
                                    <p>Un conseil: lisez cet article, vous pourrez en tirer des leçons🧐.</p>
                                </div>
                                <div class="binduz-er-meta-author">
                                    <div class="binduz-er-author accountImg">
                                        <img src="/ressources/images/account.png" alt="image">
                                        <span>Publié par <span>Marcos</span></span>
                                    </div>
                                    <div class="binduz-er-meta-list">
                                        <ul>
                                            <li><i class="fal fa-eye"></i> 5k</li>
                                            <li><i class="fal fa-heart"></i> 5k</li>
                                            <li><i class="fal fa-comments"></i> 5k</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="binduz-er-recently-viewed-area">
        <div class=" container">
            <div class="binduz-er-recently-viewed-box">
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="binduz-er-top-news-title">
                            <h3 class="binduz-er-title">Articles récemments vus</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class=" col-lg-3">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb imgElement">
                                    <img src="/ressources/images/php.png" alt="php">
                                </div>
                                <div class="binduz-er-content">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">PHP</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>2023-05-23</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb imgElement">
                                    <img src="/ressources/images/js.png" alt="js">
                                </div>
                                <div class="binduz-er-content">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">JavaScript</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>2023-05-23</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb imgElement">
                                    <img src="/ressources/images/css.png" alt="css">
                                </div>
                                <div class="binduz-er-content">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">CSS</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>2023-05-22</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-3">
                        <div class="binduz-er-video-post binduz-er-recently-viewed-item">
                            <div class="binduz-er-latest-news-item">
                                <div class="binduz-er-thumb imgElement">
                                    <img src="/ressources/images/php.png" alt=php">
                                </div>
                                <div class="binduz-er-content">
                                    <div class="binduz-er-meta-item">
                                        <div class="binduz-er-meta-categories">
                                            <a href="#">PHP</a>
                                        </div>
                                        <div class="binduz-er-meta-date">
                                            <span><i class="fal fa-calendar-alt"></i>2023-05-22</span>
                                        </div>
                                    </div>
                                    <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="binduz-er-top-news-area">
        <div class=" container">
            <div class="row">
                <div class=" col-lg-4">
                    <div class="binduz-er-top-news-title">
                        <h3 class="binduz-er-title">Actualités à la une</h3>
                    </div>
                    <div class="binduz-er-top-news-item">
                        <span>01</span>
                        <h5 class="binduz-er-title"><a href="#">Titre de l'article </a></h5>
                        <div class="binduz-er-meta-date">
                            <span><i class="fal fa-calendar-alt"></i> 2023-05-23</span>
                        </div>
                    </div>
                    <div class="binduz-er-top-news-item">
                        <span>02</span>
                        <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                        <div class="binduz-er-meta-date">
                            <span><i class="fal fa-calendar-alt"></i> 2023-05-23</span>
                        </div>
                    </div>
                    <div class="binduz-er-top-news-item">
                        <span>03</span>
                        <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                        <div class="binduz-er-meta-date">
                            <span><i class="fal fa-calendar-alt"></i> 2023-05-23</span>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-4">
                    <div class="binduz-er-top-news-title">
                        <h3 class="binduz-er-title">Articles les plus lus</h3>
                    </div>
                    <div class="binduz-er-news-viewed-most-slide">
                        <div class="binduz-er-news-viewed-most">
                            <div class="binduz-er-thumb articleImg">
                                <img src="/ressources/images/angular.png" alt="vuejs">
                            </div>
                            <div class="binduz-er-content">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">Angular JS</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-12</span>
                                    </div>
                                </div>
                                <h4 class="binduz-er-title"><a href="#">Titre de l'article</a></h4>
                                <div class="binduz-er-meta-author accountAuthor">
                                    <img src="/ressources/images/account.png" alt="image">
                                    <span>Publié par <span>Marcos</span></span>
                                </div>
                            </div>
                        </div>
                        <div class="binduz-er-news-viewed-most">
                            <div class="binduz-er-thumb articleImg">
                                <img src="/ressources/images/js.png" alt="css">
                            </div>
                            <div class="binduz-er-content">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">JavaScript</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i> 2023-05-12</span>
                                    </div>
                                </div>
                                <h4 class="binduz-er-title"><a href="#">Titre de l'article</a></h4>
                                <div class="binduz-er-meta-author accountAuthor">
                                    <img src="/ressources/images/account.png" alt="image">
                                    <span>Publié par <span>Erik</span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-4">
                    <div class="binduz-er-top-news-faq">
                        <h4 class="binduz-er-title">Pour les publicités</h4>
                        <div class="binduz-er-meta-author">
                            <span>By <span>Miranda H. Halim</span></span>
                        </div>
                        <div class="binduz-er-answare">
                            <p>Get Ask Amy delivered to your inbox every morning</p>
                        </div>
                        <div class="binduz-er-client-thumb">
                            <img src="/ressources/images/client-thumb.png" alt="">
                        </div>
                    </div>
                    <div class="binduz-er-social-list">
                        <div class="binduz-er-list">
                            <a href="#">
                                <span><i class="fab fa-facebook-f"></i> <span>15000</span> Likes</span>
                                <span>Like</span>
                            </a>
                            <a href="#">
                                <span><i class="fab fa-twitter"></i> <span>15000</span> Likes</span>
                                <span>Tweet</span>
                            </a>
                            <a href="#">
                                <span><i class="fab fa-behance"></i> <span>5k+</span> Follower</span>
                                <span>Follow</span>
                            </a>
                            <a href="#">
                                <span><i class="fab fa-youtube"></i> <span>15000</span> Subscribe</span>
                                <span>Subscribe</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="binduz-er-footer-add pb-60">
        <div class=" container">
            <div class="row">
                <div class=" col-lg-12">
                    <div class="binduz-er-footer-add-item text-center bg-prog">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="binduz-er-latest-news-area">
        <div class=" container">
            <div class="row">
                <div class=" col-lg-8">
                    <div class="binduz-er-top-news-title">
                        <h3 class="binduz-er-title">Dernières nouvelles</h3>
                    </div>
                    <div class="binduz-er-latest-news-item">
                        <div class="binduz-er-thumb lastArtImg">
                            <img src="/ressources/images/sql.png" alt="image">
                        </div>
                        <div class="binduz-er-content">
                            <div class="binduz-er-meta-categories">
                                <a href="#">SQL</a>
                            </div>
                            <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                            <div class="binduz-er-meta-item">
                                <div class="binduz-er-meta-author">
                                    <span>Publié par <span>Kola</span></span>
                                </div>
                                <div class="binduz-er-meta-date">
                                    <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="binduz-er-latest-news-item">
                        <div class="binduz-er-thumb lastArtImg">
                            <img src="/ressources/images/java.png" alt="image">
                        </div>
                        <div class="binduz-er-content">
                            <div class="binduz-er-meta-categories">
                                <a href="#">Java</a>
                            </div>
                            <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                            <div class="binduz-er-meta-item">
                                <div class="binduz-er-meta-author">
                                    <span>Publié par <span>Erik</span></span>
                                </div>
                                <div class="binduz-er-meta-date">
                                    <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="binduz-er-latest-news-item">
                        <div class="binduz-er-thumb lastArtImg">
                            <img src="/ressources/images/jquery.png" alt="image">
                        </div>
                        <div class="binduz-er-content">
                            <div class="binduz-er-meta-categories">
                                <a href="#">JQuery</a>
                            </div>
                            <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                            <div class="binduz-er-meta-item">
                                <div class="binduz-er-meta-author">
                                    <span>Publié par <span>Kola</span></span>
                                </div>
                                <div class="binduz-er-meta-date">
                                    <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="binduz-er-latest-news-item">
                        <div class="binduz-er-thumb lastArtImg">
                            <img src="/ressources/images/angular.png" alt="image">
                        </div>
                        <div class="binduz-er-content">
                            <div class="binduz-er-meta-categories">
                                <a href="#">Angular JS</a>
                            </div>
                            <h5 class="binduz-er-title"><a href="#">Titre de l'article</a></h5>
                            <div class="binduz-er-meta-item">
                                <div class="binduz-er-meta-author">
                                    <span>Publié par <span>Marcos</span></span>
                                </div>
                                <div class="binduz-er-meta-date">
                                    <span><i class="fal fa-calendar-alt"></i> 2023-05-24</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-4">
                    <div class="binduz-er-top-news-title">
                        <h3 class="binduz-er-title">Pour les publicités</h3>
                    </div>
                    <div class="binduz-er-video-post">
                        <div class="binduz-er-latest-news-item">
                            <div class="binduz-er-thumb">
                                <img src="/ressources/images/latest-news-thumb-4.jpg" alt="">
                                <div class="binduz-er-play">
                                    <a class="binduz-er-video-popup" href="#"><i class="fas fa-play"></i></a>
                                </div>
                            </div>
                            <div class="binduz-er-content">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">Technology</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                    </div>
                                </div>
                                <h5 class="binduz-er-title"><a href="#">Spruce up your Business Profile for holiday
                                        shoppers</a></h5>
                            </div>
                        </div>
                        <div class="binduz-er-latest-news-item">
                            <div class="binduz-er-thumb">
                                <img src="/ressources/images/video-post-thumb.jpg" alt="">
                                <div class="binduz-er-play">
                                    <a class="binduz-er-video-popup" href="#"><i class="fas fa-play"></i></a>
                                </div>
                            </div>
                            <div class="binduz-er-content">
                                <div class="binduz-er-meta-item">
                                    <div class="binduz-er-meta-categories">
                                        <a href="#">Technology</a>
                                    </div>
                                    <div class="binduz-er-meta-date">
                                        <span><i class="fal fa-calendar-alt"></i>24th February 2020</span>
                                    </div>
                                </div>
                                <h5 class="binduz-er-title"><a href="#">The new conversational Search experience we’re
                                        thankful for</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<?php include_once("../App/Views/FrontendUser/includes/footer.phtml") ?>