<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>MasterCode</title>
    <link rel="stylesheet" href="/ressources/css/styleLogin.css">


</head>

<body class="gray-bg">

    <div class="login-wrap">
        <div class="login-html">
            <div class="lien-master">
                <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">MasterCode</a>
            </div>
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1"
                class="tab">Connexion</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Créer un
                compte</label>
            <div class="login-form">
                <div class="sign-in-htm login-mt">
                    <form action="#">
                        <div class="group">
                            <label for="username" class="label">Pseudo</label>
                            <input id="username" type="text" class="input">
                            <p id="uname_error"></p>
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Password</label>
                            <input id="pass" type="password" class="input" data-type="password">
                            <p id="upas_error"></p>
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Se rappeler de moi</label>
                        </div>
                        <div class="group">
                            <input type="submit" id="validation_connexion" class="button" value="Connexion">
                        </div>
                    </form>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <a href="#forgot">Mot de passe oublié?</a>
                    </div>
                </div>
                <div class="sign-up-htm sign-mt">
                    <form action="#">
                        <div class="group">
                            <label for="lastName" class="label">Pseudo</label>
                            <input id="lastName" type="text" class="input">
                            <p id="name_error"></p>
                        </div>
                        <div class="group">
                            <label for="email" class="label">Adresse électronique</label>
                            <input id="email" type="text" class="input">
                            <p id="email_error"></p>
                        </div>
                        <div class="group">
                            <label for="password" class="label">Mot de passe</label>
                            <input id="password" type="password" class="input" data-type="password">
                            <p id="pas_error"></p>
                        </div>
                        <div class="group">
                            <label for="c_password" class="label">Répéter le mot de passe</label>
                            <input id="c_password" type="password" class="input" data-type="password">
                            <p id="c_pas_error"></p>
                        </div>
                        <div class="group">
                            <input type="submit" id="validation_inscription" class="button" value="Sign Up">
                        </div>
                    </form>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <label for="tab-1">Vous êtes un membre?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/ressources/js/loginAndsign.js"></script>

</body>

</html>